# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1772, 859)

        # Horizontal Layout for Buttons
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(1360, 0, 381, 841))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        # Group Box for Buttons
        self.gp_isterler = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.gp_isterler.setFont(font)
        self.gp_isterler.setObjectName("gp_isterler")

        # Buttons for Features
        self.btn_ister7 = self.create_button(self.gp_isterler, "btn_ister7", 50, 697, 301, 71, 13, "7.İSTER")
        self.btn_ister6 = self.create_button(self.gp_isterler, "btn_ister6", 50, 600, 301, 71, 13, "6.İSTER")
        self.btn_ister5 = self.create_button(self.gp_isterler, "btn_ister5", 50, 500, 301, 71, 13, "5.İSTER")
        self.btn_ister4 = self.create_button(self.gp_isterler, "btn_ister4", 50, 390, 301, 71, 13, "4.İSTER")
        self.btn_ister3 = self.create_button(self.gp_isterler, "btn_ister3", 50, 290, 301, 71, 14, "3.İSTER")
        self.btn_ister2 = self.create_button(self.gp_isterler, "btn_ister2", 50, 190, 301, 71, 13, "2.İSTER")
        self.btn_ister1 = self.create_button(self.gp_isterler, "btn_ister1", 50, 80, 301, 71, 13, "1.İSTER")

        self.horizontalLayout.addWidget(self.gp_isterler)

        # Scroll Area for Logs
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(8, 8, 331, 841))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")

        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1222, 1222))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.result_scr = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.result_scr.setMinimumSize(QtCore.QSize(1200, 1200))
        self.result_scr.setText("")
        self.result_scr.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.result_scr.setObjectName("result_scr")
        self.verticalLayout_3.addWidget(self.result_scr)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)

        # Graph Display Area
        self.lbl_graph = QtWidgets.QLabel(Form)
        self.lbl_graph.setGeometry(QtCore.QRect(350, 10, 1001, 831))
        self.lbl_graph.setText("")
        self.lbl_graph.setObjectName("lbl_graph")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.gp_isterler.setTitle(_translate("Form", "İSTERLER"))

    def create_button(self, parent, name, x, y, width, height, font_size, text):
        """Helper function to create buttons."""
        button = QtWidgets.QPushButton(parent)
        button.setGeometry(QtCore.QRect(x, y, width, height))
        font = QtGui.QFont()
        font.setPointSize(font_size)
        button.setFont(font)
        button.setObjectName(name)
        button.setText(text)
        return button


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
